spring:
  datasource:
    url: jdbc:h2:file:/app/db/h2db;
    driver-class-name: org.h2.Driver
    username: sa
    password: solora
  h2:
    console:
      enabled: true
      path: /h2db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true