-- 吸烟Counter表
CREATE TABLE smoke_timer (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     rev1 VARCHAR(100),
     rev2 VARCHAR(100),
     date VARCHAR(8),   -- yyyyMMdd
     time VARCHAR(6)    -- HHmmss
);

-- 起始日期表
CREATE TABLE IF NOT EXISTS DATE_INFO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date CHAR(14) COMMENT '日期，格式：YYYYMMDDHHmm',
    create_time CHAR(14) COMMENT '创建时间，格式：YYYYMMDDHHMMSS'
);

-- 用户表
CREATE TABLE TBL_USER (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      USERNAME VARCHAR(50) NOT NULL UNIQUE,
      PASSWORD VARCHAR(100) NOT NULL,
      REMARK VARCHAR(500),
      CREATE_TIME VARCHAR(20) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
      UPDATE_TIME VARCHAR(20) DEFAULT TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')
);
