spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

  application:
    name: 'iTimer-Server'
  profiles:
    active: 'db'
  servlet:
    # 图片上传大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
#  servlet:
#    context-path: /iTimer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jim.itimerserver.entity



timer:
  smoke_file_dir: '/Users/hsk/Desktop/'

file:
  hidden_pic_dir: '/Users/hsk/Desktop/hidden_from_phone/'
