spring:
  application:
    name: 'iTimer-Server'
  profiles:
    active: 'db'
  servlet:
    # 图片上传大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  servlet:
    context-path: /iTimer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jim.itimerserver.entity

timer:
  file_dir: '/home/jim/Desktop/'