spring:
  datasource:
    url: jdbc:h2:./dev/h2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;IFEXISTS=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: solora                  # 默认空密码
  h2:
    console:
      enabled: true             # 开启网页控制台
      path: /h2db         # 控制台访问地址
  jpa:
    hibernate:
      ddl-auto: update          # 自动建表
    show-sql: true              # 控制台显示 SQL